### ISSUE TITLE
M1: OI / Drive robot with two joysticks

### ISSUE THREAD

**Issue by jackellingwood** [frc5687/2022-robot#8]
This should allow the driver to control the basic functions of the robot with a joystick or racewheel.

**Comment by BenBernardCIS** [comment]
This is pretty broad...typically we try to make issues much more specific.

**Comment by jackellingwood** [comment]
Ok, how about driving, since we haven't gotten the shooter down yet.

**Comment by greenermoose** [comment]
I've changed the name of this issue and suggest we narrow the focus to controlling the robot with two joysticks. I believe OI from the base code assumed a game pad as controller. We want to control the robot with two joysticks. One joystick for the driver to control translation of the robot across the field, and one for the operator to control rotation and other subsystems of the robot.

**Comment by greenermoose** [comment]
This is [Milestone 1 in Good Day](https://www.goodday.work/t/y51qA1).

**Comment by greenermoose** [comment]
I got the offsets figured out. The only thing left is renaming constants and variables to use the new nomenclature for the four drive modules: NW, NE, SW and SE. We're no longer referring to drive modules as FRONT or BACK or LEFT or RIGHT because it gets confusing when the robot is rotated and we're driving with swerves.

**Comment by greenermoose** [comment]
We fixed the hardware so all offsets should be zero now.
